### ISSUE TITLE
Better errors

### ISSUE THREAD

**Issue by antoine-de** [CanalTP/mimirsbrunn#179]
I find the mimir errors quite difficult to trace.

for example, without the fix in #173  the error message is:

```
thread 'main' panicked at 'failed to bulk insert file "/home/antoine/dev/mimirsbrunn/tests/fixtures/sample-oa.csv" because: 400 Bad Request - {"error":{"root_cause":[{"type":"parse_exception","reason":"Failed to derive xcontent"}],"type":"parse_exception","reason":"Failed to derive xcontent"},"status":400}', src/bin/openaddresses2mimir.rs:133:22
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```
and if we ask for the backtrace, it's not much more helpful
```
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:68
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:57
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:577
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:538
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   7: openaddresses2mimir::index_oa
             at src/bin/openaddresses2mimir.rs:133
   8: openaddresses2mimir::main
             at src/bin/openaddresses2mimir.rs:175
   9: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:101
  10: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:459
             at /checkout/src/libstd/panic.rs:365
             at /checkout/src/libstd/rt.rs:58
```

I think using the [failure crate](https://crates.io/crates/failure) might be a lot nicer if you think it's stable enough.

Are you Ok with this ?

**Comment by TeXitoi** [comment]
We will accept a PR on converting mimirsbrunn to the failure crate with pleasure.

**Comment by antoine-de** [comment]
I think we can close this, the erros are not yet perfect, but we use `failure` now, so it's much better.
